### ISSUE TITLE
Missing dependency: pytablewriter

### ISSUE THREAD

**Issue by joaopalmeiro** [thombashi/pathvalidate-cli#1]
Hi! 👋 

I was trying to run the CLI (via `pipx run pathvalidate-cli sanitize "9.1-notebook_name.ipynb"`), and it appears that there is a missing dependency ([pytablewriter](https://github.com/thombashi/pathvalidate-cli/blob/v0.0.1/pathvalidate_cli/main.py#L8)) in the [`requirements.txt` file](https://github.com/thombashi/pathvalidate-cli/blob/v0.0.1/requirements/requirements.txt):

```plain
NOTE: running app 'pathvalidate' from 'pathvalidate-cli'
Traceback (most recent call last):
  File "/Users/joao.palmeiro/.local/pipx/.cache/84217a794ad66ce/bin/pathvalidate", line 5, in <module>
    from pathvalidate_cli.main import cmd
  File "/Users/joao.palmeiro/.local/pipx/.cache/84217a794ad66ce/lib/python3.12/site-packages/pathvalidate_cli/main.py", line 8, in <module>
    import pytablewriter as ptw
ModuleNotFoundError: No module named 'pytablewriter'
```

If I'm understanding this correctly, let me know if I can help in any way. Thanks!

**Comment by thombashi** [comment]
@joaopalmeiro 
Thank you for your report.
That missing dependency was unintentional.
I have fixed it in `pathvalidate-cli v0.0.2`.
